// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Praksa_projectV1.Models;

public partial class Employee
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? DepartmentId { get; set; }

    public int? JobId { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public DateOnly? Birthday { get; set; }

    public long? Jmbg { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string FullName { get; set; }

    public bool IsActive { get; set; }

    public string IsActiveText { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<EmployeeProject> EmployeeProjects { get; set; } = new List<EmployeeProject>();

    public virtual Job Job { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<WorkingCard> WorkingCards { get; set; } = new List<WorkingCard>();
}