// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Praksa_projectV1.Models;

public partial class ExceptionLog
{
    public int Id { get; set; }

    public string Message { get; set; }

    public string StackTrace { get; set; }

    public string Source { get; set; }

    public DateTime? Timestamp { get; set; }
}