// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Praksa_projectV1.Models;

public partial class Project
{
    public int Id { get; set; }

    public int? LocationId { get; set; }

    public int? TypeId { get; set; }

    public string Name { get; set; }

    public string Status { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public virtual ICollection<EmployeeProject> EmployeeProjects { get; set; } = new List<EmployeeProject>();

    public virtual Location Location { get; set; }

    public virtual Type Type { get; set; }

    public virtual ICollection<WorkingCard> WorkingCards { get; set; } = new List<WorkingCard>();
}