// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Praksa_projectV1.Models;

public partial class Type
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();
}