// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Praksa_projectV1.Models;

public partial class WorkingCard
{
    public int Id { get; set; }

    public int? EmployeeId { get; set; }

    public int? ProjectId { get; set; }

    public DateOnly? Date { get; set; }

    public decimal? Hours { get; set; }

    public int? ActivityId { get; set; }

    public virtual Activity Activity { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Project Project { get; set; }
}